### ISSUE TITLE
&nbsp; not supported

### ISSUE THREAD

**Issue by thomas-lcdp** [openhtmltopdf/openhtmltopdf#76] opened 2024-11-04 10:42 UTC
Hello,

If the html has one &nbsp; we encountered an error:

`SAX XMLReader in use (parser): com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser
The entity "nbsp" was referenced, but not declared.
Unhandled exception. Can't load the XML resource (using TRaX transformer). org.xml.sax.SAXParseException; lineNumber: 38; columnNumber: 21; The entity "nbsp" was referenced, but not declared.`

You can easily reproduce in https://sandbox.openhtmltopdf.com/ by replacing text by Hello World!&nbsp;toto

**Comment by thomas-lcdp** [comment] 2024-11-04 14:17
OK, check the doctype...
It would be great to do not modify the generic html but add an option to PdfRendererBuilder

**Comment by syjer** [comment] 2024-11-09 16:34
hi @thomas-lcdp , the simplest way to handle the entities is to use an html parser and then feed the DOM to openhtmltopdf.

**Comment by siegelzc** [comment] 2024-11-14 03:37
From the readme:
> The native XML parser cannot interpret the full HTML specification. We recommend users to utilize the [Jsoup](https://jsoup.org/) library to pre-emptively parse the HTML file before passing a Document object to the PDF renderer.

The `&nbsp;` entity should work as intended if you use Jsoup as @syjer was alluding to.

**Comment by siegelzc** [comment] 2024-11-14 03:38
Closing for now, if you try Jsoup and that isn't working, we will reopen the discussion.

**Closed by siegelzc** 2024-11-14 03:38 UTC
